/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.Frontend.PanelesSimulacion;

import com.mycompany.Backend.GestorDeDatos.LectorArchivoCSV;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kenny
 */
public class PanelEdicionDeArchivos extends javax.swing.JPanel {

    private String carpetaElegida;

    public PanelEdicionDeArchivos() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelTituloEdicionDeAviones = new javax.swing.JPanel();
        labelEdicionAviones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeAviones = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        labelTituloEdicionPistas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDePistas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaDeEstaciones = new javax.swing.JTable();
        botonSalir = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 51, 51));

        panelTitulo.setBackground(new java.awt.Color(255, 102, 204));

        labelTitulo.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("EDICION DE DATOS");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
        );

        panelTituloEdicionDeAviones.setBackground(new java.awt.Color(255, 204, 204));

        labelEdicionAviones.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelEdicionAviones.setForeground(new java.awt.Color(0, 0, 0));
        labelEdicionAviones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEdicionAviones.setText("Edicion de aviones");

        javax.swing.GroupLayout panelTituloEdicionDeAvionesLayout = new javax.swing.GroupLayout(panelTituloEdicionDeAviones);
        panelTituloEdicionDeAviones.setLayout(panelTituloEdicionDeAvionesLayout);
        panelTituloEdicionDeAvionesLayout.setHorizontalGroup(
            panelTituloEdicionDeAvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelEdicionAviones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTituloEdicionDeAvionesLayout.setVerticalGroup(
            panelTituloEdicionDeAvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelEdicionAviones, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        tablaDeAviones.setBackground(new java.awt.Color(153, 255, 153));
        tablaDeAviones.setForeground(new java.awt.Color(0, 0, 0));
        tablaDeAviones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDeAviones);

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));

        labelTituloEdicionPistas.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelTituloEdicionPistas.setForeground(new java.awt.Color(0, 0, 0));
        labelTituloEdicionPistas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloEdicionPistas.setText("Edicion de pistas                                                    Edicion de estaciones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTituloEdicionPistas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTituloEdicionPistas, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        TablaDePistas.setBackground(new java.awt.Color(102, 255, 204));
        TablaDePistas.setForeground(new java.awt.Color(0, 0, 0));
        TablaDePistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaDePistas);

        TablaDeEstaciones.setBackground(new java.awt.Color(255, 153, 153));
        TablaDeEstaciones.setForeground(new java.awt.Color(0, 0, 0));
        TablaDeEstaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TablaDeEstaciones);

        botonSalir.setBackground(new java.awt.Color(255, 51, 153));
        botonSalir.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(0, 0, 0));
        botonSalir.setText("Volver y no guardar cambios");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonGuardar.setBackground(new java.awt.Color(0, 255, 51));
        botonGuardar.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        botonGuardar.setText("Guardar cambio");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTituloEdicionDeAviones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTituloEdicionDeAviones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
          if (!validarTablaAviones()) {
            return;
        }

        if (!validarTablaPistas()) {
            return;
        }

        if (!validarTablaEstaciones()) {
            return;
        }

        guardarCambiosCSV();

        JOptionPane.showMessageDialog(this, "Datos guardados correctamente.");
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        reiniciarArchivo();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void guardarCambiosCSV(){
        guardarTablaAviones();
        guardarTablaPistas();
        guardarTablaEstaciones();
    }
    
   public void editarTablas() {

        LectorArchivoCSV lector = new LectorArchivoCSV(carpetaElegida);

        String[][] datosAviones = lector.leerArchivo("aviones.csv");
        String[][] datosAterrizaje = lector.leerArchivo("aterrizaje.csv");
        String[][] datosDespegue = lector.leerArchivo("despegue.csv");
        String[][] datosControl = lector.leerArchivo("control.csv");
        String[][] datosMantenimiento = lector.leerArchivo("mantenimiento.csv");
        String[][] datosDesbordaje = lector.leerArchivo("desbordaje.csv");

        String[][] datosPistas = unirMatrices(datosAterrizaje, datosDespegue);
        String[][] datosEstaciones = unirMatrices(
                datosControl,
                datosMantenimiento,
                datosDesbordaje
        );

            // TABLA AVIONES
            DefaultTableModel modeloAviones = new DefaultTableModel(
                    datosAviones,
                    new String[]{"ID", "Combustible", "Capacidad Min", "Capacidad Max", "Tipo"}
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    // solo editar ID y Combustible
                    return column == 0 || column == 1;
                }
            };

            // TABLA PISTAS
            DefaultTableModel modeloPistas = new DefaultTableModel(
                    datosPistas,
                    new String[]{"Tipo", "ID", "Capacidad"}
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    // bloquear Tipo
                    return column != 0;
                }
            };

            // TABLA ESTACIONES
            DefaultTableModel modeloEstaciones = new DefaultTableModel(
                    datosEstaciones,
                    new String[]{"Tipo", "ID", "Capacidad"}
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    // bloquear Tipo
                    return column != 0;
                }
            };

            tablaDeAviones.setModel(modeloAviones);
            TablaDePistas.setModel(modeloPistas);
            TablaDeEstaciones.setModel(modeloEstaciones);
    }
   
   private String[][] unirMatrices(String[][]... matrices) {

        int totalFilas = 0;

        for (String[][] matriz : matrices) {
            totalFilas += matriz.length;
        }

        String[][] resultado = new String[totalFilas][];

        int indice = 0;

        for (String[][] matriz : matrices) {
            for (String[] fila : matriz) {
                resultado[indice] = fila;
                indice++;
            }
        }

        return resultado;
    }
   
   
   
   private boolean validarTablaAviones() {

        DefaultTableModel modelo = (DefaultTableModel) tablaDeAviones.getModel();

        for (int fila = 0; fila < modelo.getRowCount(); fila++) {

            try {
                int id = Integer.parseInt(
                        modelo.getValueAt(fila, 0).toString().trim()
                );

                int combustible = Integer.parseInt(
                        modelo.getValueAt(fila, 1).toString().trim()
                );

                if (id <= 0 || combustible <= 0) {
                    throw new NumberFormatException();
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(  this, "Error en tabla Aviones, fila " + (fila + 1)  + ". ID y combustible deben ser numeros mayores a 0."
                );
                return false;
            }
        }

        return true;
    }
   
   private boolean validarTablaPistas() {

        DefaultTableModel modelo = (DefaultTableModel) TablaDePistas.getModel();

        for (int fila = 0; fila < modelo.getRowCount(); fila++) {

            try {
                int id = Integer.parseInt(
                        modelo.getValueAt(fila, 1).toString().trim()
                );

                int capacidad = Integer.parseInt(
                        modelo.getValueAt(fila, 2).toString().trim()
                );

                if (id <= 0 || capacidad <= 0) {
                    throw new NumberFormatException();
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(
                        this,   "Error en tabla Pistas, fila " + (fila + 1) + ". ID y capacidad deben ser números mayores a 0."
                );
                return false;
            }
        }

        return true;
    }
   
   private boolean validarTablaEstaciones() {

        DefaultTableModel modelo = (DefaultTableModel) TablaDeEstaciones.getModel();

        for (int fila = 0; fila < modelo.getRowCount(); fila++) {

            try {
                int id = Integer.parseInt(
                        modelo.getValueAt(fila, 1).toString().trim()
                );

                int capacidad = Integer.parseInt(
                        modelo.getValueAt(fila, 2).toString().trim()
                );

                if (id <= 0 || capacidad <= 0) {
                    throw new NumberFormatException();
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(
                        this,
                        "Error en tabla Estaciones, fila " + (fila + 1)
                        + ". ID y capacidad deben ser números mayores a 0."
                );
                return false;
            }
        }

        return true;
    }
   
   private void guardarTablaAviones() {

        File archivo = new File("datos/" + carpetaElegida + "/aviones.csv");

        try (FileWriter fileWriter = new FileWriter(archivo);
             PrintWriter writer = new PrintWriter(fileWriter)) {

            DefaultTableModel modelo = (DefaultTableModel) tablaDeAviones.getModel();

            for (int fila = 0; fila < modelo.getRowCount(); fila++) {

                String linea = modelo.getValueAt(fila, 0) + ","   + modelo.getValueAt(fila, 1) + ","  + modelo.getValueAt(fila, 2) + ","
                        + modelo.getValueAt(fila, 3) + "," + modelo.getValueAt(fila, 4);

                writer.println(linea);
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
   
   private void guardarTablaPistas() {

        File archivoAterrizaje = new File("datos/" + carpetaElegida + "/aterrizaje.csv");
        File archivoDespegue = new File("datos/" + carpetaElegida + "/despegue.csv");

        try (
            FileWriter fwAterrizaje = new FileWriter(archivoAterrizaje);
            PrintWriter writerAterrizaje = new PrintWriter(fwAterrizaje);

            FileWriter fwDespegue = new FileWriter(archivoDespegue);
            PrintWriter writerDespegue = new PrintWriter(fwDespegue)
        ) {

            DefaultTableModel modelo = (DefaultTableModel) TablaDePistas.getModel();

            for (int fila = 0; fila < modelo.getRowCount(); fila++) {

                String tipo = modelo.getValueAt(fila, 0).toString();

                String linea = modelo.getValueAt(fila, 0) + ","
                        + modelo.getValueAt(fila, 1) + ","
                        + modelo.getValueAt(fila, 2);

                if (tipo.equalsIgnoreCase("ATERRIZAJE")) {
                    writerAterrizaje.println(linea);
                } else {
                    writerDespegue.println(linea);
                }
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
   
   private void guardarTablaEstaciones() {

        File archivoControl = new File("datos/" + carpetaElegida + "/control.csv");
        File archivoMantenimiento = new File("datos/" + carpetaElegida + "/mantenimiento.csv");
        File archivoDesbordaje = new File("datos/" + carpetaElegida + "/desbordaje.csv");
        

        try (
            FileWriter fwControl = new FileWriter(archivoControl);
            PrintWriter writerControl = new PrintWriter(fwControl);

            FileWriter fwMantenimiento = new FileWriter(archivoMantenimiento);
            PrintWriter writerMantenimiento = new PrintWriter(fwMantenimiento);

            FileWriter fwDesbordaje = new FileWriter(archivoDesbordaje);
            PrintWriter writerDesbordaje = new PrintWriter(fwDesbordaje)
        ) {

            DefaultTableModel modelo = (DefaultTableModel) TablaDeEstaciones.getModel();

            for (int fila = 0; fila < modelo.getRowCount(); fila++) {

                String tipo = modelo.getValueAt(fila, 0).toString();

                String linea = modelo.getValueAt(fila, 0) + ","
                        + modelo.getValueAt(fila, 1) + ","
                        + modelo.getValueAt(fila, 2);

                if (tipo.equalsIgnoreCase("CONTROL")) {
                    writerControl.println(linea);

                } else if (tipo.equalsIgnoreCase("MANTENIMIENTO")) {
                    writerMantenimiento.println(linea);

                } else {
                    writerDesbordaje.println(linea);
                }
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

   
   private boolean verificarCarpetaExistente(File archivo){
       if(archivo.exists()){
           return true;
       } else {
           return false;
       }
       
   }
   
    public void setArchivoElegido(String archivoElegido) {
        this.carpetaElegida = archivoElegido;
    }
    
   private void reiniciarArchivo() {
        carpetaElegida = null;

        tablaDeAviones.setModel(new DefaultTableModel());
        TablaDePistas.setModel(new DefaultTableModel());
        TablaDeEstaciones.setModel(new DefaultTableModel());
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDeEstaciones;
    private javax.swing.JTable TablaDePistas;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelEdicionAviones;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTituloEdicionPistas;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelTituloEdicionDeAviones;
    private javax.swing.JTable tablaDeAviones;
    // End of variables declaration//GEN-END:variables
}
