/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.Frontend.PanelesSimulacion;

import com.mycompany.Backend.Constructores.ConstructorPartida;
import com.mycompany.Frontend.PanelesDeEdicion.PanelMenuDeEleccion;
import com.mycompany.Frontend.VentanaInicial.VentanaInicial;
import java.awt.CardLayout;

/**
 *
 * @author Kenny
 */
public class PanelContenedorSimulacion extends javax.swing.JPanel {

    private ConstructorPartida construirPartida;
    private final PanelEdicionDeArchivos panelEdicion;
    private final PanelMenuDeEleccion menuEdicion;
    private final PanelElegirRutaLog elegirRuta;
    private final PanelSimulacion panelSimulacion;
    private final PanelConfiguracionTiempos panelConfiguracion;
    private final VentanaInicial ventanaInicial;
    
    private final String PANEL_EDICION = "PANEL EDICION";
    private final String MENU_EDICION = "MENU EDICION";
    private final String ELEGIR_RUTA = "RUTA DE LOGS";
    private final String PANEL_SIMULACION = "PANEL SIMULACION";
    private final String PANEL_CONFIGURACION ="PANEL CONFIGURACION";
    
    /**
     * Creates new form PanelContenedorSimulacion
     * @param ventanaInicial
     */
    public PanelContenedorSimulacion(VentanaInicial ventanaInicial) {
        this.ventanaInicial = ventanaInicial;
        this.menuEdicion = new PanelMenuDeEleccion(ventanaInicial, this);
        this.elegirRuta = new PanelElegirRutaLog(this);
        this.panelSimulacion = new PanelSimulacion(this);
        this.panelConfiguracion = new PanelConfiguracionTiempos(this);
        this.panelEdicion = new PanelEdicionDeArchivos();
        this.construirPartida = null;
        initComponents();
        agregarPaneles();
        irAEleccionDeDatos();
    }
    
    private void agregarPaneles(){
        this.add(panelEdicion, PANEL_EDICION);
        this.add(menuEdicion, MENU_EDICION);
        this.add(elegirRuta, ELEGIR_RUTA);
        this.add(panelSimulacion, PANEL_SIMULACION);
        this.add(panelConfiguracion, PANEL_CONFIGURACION);
    }
    
    public final void irAEleccionDeDatos(){
        cambiarDePaneles(MENU_EDICION);
    }
    
    public void irAEleccionDeRuta(){
        cambiarDePaneles(ELEGIR_RUTA);
    }
    
    public void irASimulacion(){
        cambiarDePaneles(PANEL_SIMULACION);
    }
    
    private void cambiarDePaneles(String panel){
        CardLayout cardLayout = (CardLayout) this.getLayout();
        cardLayout.show(this, panel);
    }
    
    public void irAConfiguracionTiempos(){
        cambiarDePaneles(PANEL_CONFIGURACION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents

    public ConstructorPartida getConstruirPartida() {
        return construirPartida;
    }

    public void setConstruirPartida(ConstructorPartida construirPartida) {
        this.construirPartida = construirPartida;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
