/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.Frontend.PanelesSimulacion;

import com.mycompany.Frontend.PanelesSimulacion.ContenedoresDeDatos.PanelAterrizaje;
import com.mycompany.Frontend.PanelesSimulacion.ContenedoresDeDatos.PanelDeVuelo;
import com.mycompany.Frontend.PanelesSimulacion.ContenedoresDeDatos.PanelDespegue;
import com.mycompany.Frontend.PanelesSimulacion.ContenedoresDeDatos.PanelEstacionesDeControl;
import com.mycompany.Frontend.PanelesSimulacion.ContenedoresDeDatos.PanelEstacionesDeMantenimiento;
import com.mycompany.Frontend.PanelesSimulacion.ContenedoresDeDatos.PanelEstacionesDesbordaje;
import com.mycompany.Frontend.PanelesSimulacion.ContenedoresDeDatos.PanelLogs;
import java.awt.CardLayout;

/**
 *
 * @author Kenny
 */
public class PanelSimulacion extends javax.swing.JPanel implements Runnable {
    
    private boolean simulacionActiva;
    private final PanelContenedorSimulacion panelContenedorSimulacion;
    private final PanelAterrizaje aterrizaje;
    private final PanelDeVuelo panelVuelo;
    private final PanelDespegue panelDespegue;
    private final PanelEstacionesDeControl panelControl;
    private final PanelEstacionesDeMantenimiento panelMantenimiento;
    private final PanelEstacionesDesbordaje panelDesbordaje;
    private final PanelLogs panelLogs;
    
    private final String PANEL_DE_ATERRIZAJE = "PANEL DE ATERRIZAJE";
    private final String PANEL_DE_VUELO = "PANEL DE VUELO";
    private final String PANEL_DESPEJE = "PANEL DESPEJE";
    private final String PANEL_CONTROL = "PANEL CONTROL";
    private final String PANEL_MANTENIMIENTO = "PANEL MANTENIMIENTO";
    private final String PANEL_DESBORDAJE = "PANEL DESBORDAJE";
    private final String PANEL_LOGS = "PANEL LOGS";
    
    /**
     * Creates new form PanelSimulacion
     * @param panelContenedorSimulacion
     */
    public PanelSimulacion(PanelContenedorSimulacion panelContenedorSimulacion) {
        this.panelContenedorSimulacion = panelContenedorSimulacion;
        this.aterrizaje = new PanelAterrizaje(this);
        this.panelVuelo = new PanelDeVuelo(this);
        this.panelDespegue = new PanelDespegue(this);
        this.panelControl = new PanelEstacionesDeControl(this);
        this.panelMantenimiento = new PanelEstacionesDeMantenimiento(this);
        this.panelDesbordaje = new PanelEstacionesDesbordaje(this);
        this.panelLogs = new PanelLogs(this);
        this.simulacionActiva = false;
        initComponents();
        agregarPaneles();
        botonPausar.setEnabled(false);
        botonGuardar.setEnabled(false);
        botonFinalizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedorBotones = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        botonIniciar = new javax.swing.JButton();
        botonPausar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonControl = new javax.swing.JButton();
        botonMantenimiento = new javax.swing.JButton();
        botonDesbordaje = new javax.swing.JButton();
        botonDespegue = new javax.swing.JButton();
        botonAterrizaje = new javax.swing.JButton();
        botonVuelos = new javax.swing.JButton();
        botonLogs = new javax.swing.JButton();
        botonFinalizar = new javax.swing.JButton();
        botonEdicion = new javax.swing.JButton();
        panelContenedorDatosSimulacion = new javax.swing.JPanel();

        setBackground(new java.awt.Color(102, 102, 255));

        PanelContenedorBotones.setBackground(new java.awt.Color(255, 102, 102));

        labelTitulo.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("SIMULACION ");

        botonIniciar.setBackground(new java.awt.Color(255, 204, 153));
        botonIniciar.setForeground(new java.awt.Color(0, 0, 0));
        botonIniciar.setText("Iniciar");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });

        botonPausar.setBackground(new java.awt.Color(204, 255, 204));
        botonPausar.setForeground(new java.awt.Color(0, 0, 0));
        botonPausar.setText("Pausar");
        botonPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPausarActionPerformed(evt);
            }
        });

        botonGuardar.setBackground(new java.awt.Color(51, 102, 255));
        botonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        botonGuardar.setText("Guardar Simulacion");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonControl.setBackground(new java.awt.Color(153, 255, 153));
        botonControl.setForeground(new java.awt.Color(0, 0, 0));
        botonControl.setText("Estaciones de control");
        botonControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonControlActionPerformed(evt);
            }
        });

        botonMantenimiento.setBackground(new java.awt.Color(204, 255, 51));
        botonMantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        botonMantenimiento.setText("Estaciones de mantenimiento");
        botonMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMantenimientoActionPerformed(evt);
            }
        });

        botonDesbordaje.setBackground(new java.awt.Color(255, 153, 255));
        botonDesbordaje.setForeground(new java.awt.Color(0, 0, 0));
        botonDesbordaje.setText("Estaciones de desbordaje");
        botonDesbordaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDesbordajeActionPerformed(evt);
            }
        });

        botonDespegue.setBackground(new java.awt.Color(153, 255, 153));
        botonDespegue.setForeground(new java.awt.Color(0, 0, 0));
        botonDespegue.setText("Pistas de despegue");
        botonDespegue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDespegueActionPerformed(evt);
            }
        });

        botonAterrizaje.setBackground(new java.awt.Color(102, 255, 153));
        botonAterrizaje.setForeground(new java.awt.Color(0, 0, 0));
        botonAterrizaje.setText("Pistas de aterrizaje");
        botonAterrizaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAterrizajeActionPerformed(evt);
            }
        });

        botonVuelos.setBackground(new java.awt.Color(255, 153, 102));
        botonVuelos.setForeground(new java.awt.Color(0, 0, 0));
        botonVuelos.setText("Aviones en vuelo");
        botonVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVuelosActionPerformed(evt);
            }
        });

        botonLogs.setBackground(new java.awt.Color(102, 255, 204));
        botonLogs.setForeground(new java.awt.Color(0, 0, 0));
        botonLogs.setText("Logs");
        botonLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLogsActionPerformed(evt);
            }
        });

        botonFinalizar.setBackground(new java.awt.Color(255, 51, 255));
        botonFinalizar.setForeground(new java.awt.Color(0, 0, 0));
        botonFinalizar.setText("Finalizar");
        botonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });

        botonEdicion.setBackground(new java.awt.Color(102, 102, 255));
        botonEdicion.setForeground(new java.awt.Color(0, 0, 0));
        botonEdicion.setText("Editar/Crear");

        javax.swing.GroupLayout PanelContenedorBotonesLayout = new javax.swing.GroupLayout(PanelContenedorBotones);
        PanelContenedorBotones.setLayout(PanelContenedorBotonesLayout);
        PanelContenedorBotonesLayout.setHorizontalGroup(
            PanelContenedorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenedorBotonesLayout.createSequentialGroup()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelContenedorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonPausar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelContenedorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonMantenimiento)
                    .addComponent(botonControl, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDesbordaje, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelContenedorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAterrizaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonDespegue, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(botonVuelos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelContenedorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonLogs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(botonEdicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelContenedorBotonesLayout.setVerticalGroup(
            PanelContenedorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelContenedorBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelContenedorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonControl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDespegue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelContenedorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonPausar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAterrizaje, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelContenedorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelContenedorBotonesLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(PanelContenedorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonDesbordaje, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonVuelos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelContenedorBotonesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonEdicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelContenedorDatosSimulacion.setBackground(new java.awt.Color(102, 255, 153));
        panelContenedorDatosSimulacion.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedorBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContenedorDatosSimulacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelContenedorBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenedorDatosSimulacion, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        // TODO add your handling code here:{
        botonIniciar.setEnabled(false);
        botonPausar.setEnabled(true);
        botonEdicion.setEnabled(false);
        activarSimulacion();
        Thread hilo = new Thread(this);
        hilo.start();
        panelContenedorSimulacion.getSimulacion().iniciarSimulacion();
    }//GEN-LAST:event_botonIniciarActionPerformed

    private void botonDespegueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDespegueActionPerformed
        // TODO add your handling code here:
        panelDespegue.cargarCuadricula();
        irADespeje();
    }//GEN-LAST:event_botonDespegueActionPerformed

    private void botonPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPausarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPausarActionPerformed

    private void botonDesbordajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDesbordajeActionPerformed
        // TODO add your handling code here:
        panelDesbordaje.cargarCuadricula();
        irADesbordaje();
    }//GEN-LAST:event_botonDesbordajeActionPerformed

    private void botonVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVuelosActionPerformed
        // TODO add your handling code here:
        panelVuelo.mostrarDatosTabla();
        irAVuelos();
    }//GEN-LAST:event_botonVuelosActionPerformed

    private void botonAterrizajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAterrizajeActionPerformed
        // TODO add your handling code here:
        aterrizaje.cargarCuadricula();
        irAterrizaje();
    }//GEN-LAST:event_botonAterrizajeActionPerformed

    private void botonLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLogsActionPerformed
        // TODO add your handling code here:
        irALogs();
    }//GEN-LAST:event_botonLogsActionPerformed

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFinalizarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonControlActionPerformed
        // TODO add your handling code here:
        panelControl.cargarCuadricula();
        irAControl();
    }//GEN-LAST:event_botonControlActionPerformed

    private void botonMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMantenimientoActionPerformed
            // TODO add your handling code here:
            panelMantenimiento.cargarCuadricula();
            irAMantenimiento();
    }//GEN-LAST:event_botonMantenimientoActionPerformed

    private void agregarPaneles(){
        panelContenedorDatosSimulacion.add(aterrizaje, PANEL_DE_ATERRIZAJE);
        panelContenedorDatosSimulacion.add(panelVuelo, PANEL_DE_VUELO);
        panelContenedorDatosSimulacion.add(panelDespegue, PANEL_DESPEJE);
        panelContenedorDatosSimulacion.add(panelControl, PANEL_CONTROL);
        panelContenedorDatosSimulacion.add(panelMantenimiento, PANEL_MANTENIMIENTO);
        panelContenedorDatosSimulacion.add(panelDesbordaje, PANEL_DESBORDAJE);
        panelContenedorDatosSimulacion.add(panelLogs, PANEL_LOGS);
    }
    
    public void cambiarDePaneles(String nombreDePanel){
        CardLayout cardlayout = (CardLayout) panelContenedorDatosSimulacion.getLayout();
        cardlayout.show(panelContenedorDatosSimulacion, nombreDePanel);
    }
    
    public void irAterrizaje(){
        cambiarDePaneles(PANEL_DE_ATERRIZAJE);
    }
    
    public void irAVuelos(){
        cambiarDePaneles(PANEL_DE_VUELO);
    }
    
    public void irADespeje(){
        cambiarDePaneles(PANEL_DESPEJE);
    }
    
    public void irAControl(){
        cambiarDePaneles(PANEL_CONTROL);
    }
    
    public void irAMantenimiento(){
        cambiarDePaneles(PANEL_MANTENIMIENTO);
    }
    
    public void irADesbordaje(){
        cambiarDePaneles(PANEL_DESBORDAJE);
    }
    
    public void irALogs(){
        cambiarDePaneles(PANEL_LOGS);
    }

    public PanelContenedorSimulacion getPanelContenedorSimulacion() {
        return panelContenedorSimulacion;
    }
    
       /* private final PanelAterrizaje aterrizaje;
    private final PanelDeVuelo panelVuelo;
    private final PanelDespegue panelDespegue;
    private final PanelEstacionesDeControl panelControl;
    private final PanelEstacionesDeMantenimiento panelMantenimiento;
    private final PanelEstacionesDesbordaje panelDesbordaje;
    private final PanelLogs panelLogs;*/
    
    private void actualizarDatos(){
        aterrizaje.actualizarPaneles();
        panelVuelo.mostrarDatosTabla();
        panelDespegue.cargarCuadricula();
        panelControl.cargarCuadricula();
        panelMantenimiento.cargarCuadricula();
        panelDesbordaje.cargarCuadricula();
    }
    
    public void activarSimulacion(){
        simulacionActiva = true;
    }
    
    public void desactivarSimulacion(){
        simulacionActiva = false;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedorBotones;
    private javax.swing.JButton botonAterrizaje;
    private javax.swing.JButton botonControl;
    private javax.swing.JButton botonDesbordaje;
    private javax.swing.JButton botonDespegue;
    private javax.swing.JButton botonEdicion;
    private javax.swing.JButton botonFinalizar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonLogs;
    private javax.swing.JButton botonMantenimiento;
    private javax.swing.JButton botonPausar;
    private javax.swing.JButton botonVuelos;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelContenedorDatosSimulacion;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void run() {

        while (simulacionActiva) {

            actualizarDatos();

            try {
                Thread.sleep(500);
            } catch (InterruptedException e) {
                break;
            }
        }
    }
}
