/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.Frontend.PanelesSimulacion;

/**
 *
 * @author Kenny
 */
public class PanelConfiguracionTiempos extends javax.swing.JPanel {

    /**
     * Creates new form PanelConfiguracionTiempos
     */
    public PanelConfiguracionTiempos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelDeTiempos = new javax.swing.JPanel();
        labelCombustible = new javax.swing.JLabel();
        tiempoCombustible = new javax.swing.JTextField();
        labelAterrizaje = new javax.swing.JLabel();
        tiempoDeAterrizaje = new javax.swing.JTextField();
        labelDesbordaje = new javax.swing.JLabel();
        tiempoDesbordaje = new javax.swing.JTextField();
        labelMantenimiento = new javax.swing.JLabel();
        tiempoDeMantenimiento = new javax.swing.JTextField();
        labelDespegue = new javax.swing.JLabel();
        tiempoDeDespegue = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        botonIniciarSimulacion = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 102));
        setForeground(new java.awt.Color(153, 255, 153));

        panelTitulo.setBackground(new java.awt.Color(255, 51, 51));

        labelTitulo.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Configuracion de tiempos");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelDeTiempos.setBackground(new java.awt.Color(255, 102, 255));

        labelCombustible.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelCombustible.setForeground(new java.awt.Color(0, 0, 0));
        labelCombustible.setText("Tiempo de consumo de un galon de combustible: ");

        labelAterrizaje.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelAterrizaje.setForeground(new java.awt.Color(0, 0, 0));
        labelAterrizaje.setText("Tiempo de aterrizaje: ");

        labelDesbordaje.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelDesbordaje.setForeground(new java.awt.Color(0, 0, 0));
        labelDesbordaje.setText("Tiempo de desbordaje: ");

        labelMantenimiento.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelMantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        labelMantenimiento.setText("Tiempo de mantenimiento: ");

        labelDespegue.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelDespegue.setForeground(new java.awt.Color(0, 0, 0));
        labelDespegue.setText("Tiempo de despegue: ");

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setForeground(new java.awt.Color(0, 153, 102));

        botonIniciarSimulacion.setBackground(new java.awt.Color(51, 51, 255));
        botonIniciarSimulacion.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        botonIniciarSimulacion.setForeground(new java.awt.Color(0, 0, 0));
        botonIniciarSimulacion.setText("Ir a simulacion");

        botonVolver.setBackground(new java.awt.Color(102, 255, 102));
        botonVolver.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(0, 0, 0));
        botonVolver.setText("Volver al menu anterior");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(botonIniciarSimulacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(botonIniciarSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDeTiemposLayout = new javax.swing.GroupLayout(panelDeTiempos);
        panelDeTiempos.setLayout(panelDeTiemposLayout);
        panelDeTiemposLayout.setHorizontalGroup(
            panelDeTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeTiemposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDeTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelDespegue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDesbordaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAterrizaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCombustible, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(panelDeTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tiempoDeMantenimiento)
                    .addComponent(tiempoDeDespegue)
                    .addComponent(tiempoCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempoDeAterrizaje)
                    .addComponent(tiempoDesbordaje))
                .addGap(63, 63, 63))
            .addGroup(panelDeTiemposLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDeTiemposLayout.setVerticalGroup(
            panelDeTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeTiemposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDeTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempoCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDeTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAterrizaje, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempoDeAterrizaje, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDeTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDesbordaje, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempoDesbordaje, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDeTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempoDeMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDeTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDespegue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempoDeDespegue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDeTiempos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDeTiempos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciarSimulacion;
    private javax.swing.JButton botonVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAterrizaje;
    private javax.swing.JLabel labelCombustible;
    private javax.swing.JLabel labelDesbordaje;
    private javax.swing.JLabel labelDespegue;
    private javax.swing.JLabel labelMantenimiento;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelDeTiempos;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTextField tiempoCombustible;
    private javax.swing.JTextField tiempoDeAterrizaje;
    private javax.swing.JTextField tiempoDeDespegue;
    private javax.swing.JTextField tiempoDeMantenimiento;
    private javax.swing.JTextField tiempoDesbordaje;
    // End of variables declaration//GEN-END:variables
}
