/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.Frontend.PanelesSimulacion;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Kenny
 */
public class PanelElegirRutaLog extends javax.swing.JPanel {

    private final PanelContenedorSimulacion contenedorSimulacion;
    
    /**
     * Creates new form PanelElegirRutaLog
     * @param contenedorSimulacion
     */
    public PanelElegirRutaLog(PanelContenedorSimulacion contenedorSimulacion) {
        this.contenedorSimulacion = contenedorSimulacion;
        initComponents();
        configurarFileChooser();
        eleccionParaLogs.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        eleccionParaLogs.setControlButtonsAreShown(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eleccionParaLogs = new javax.swing.JFileChooser();
        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();

        panelTitulo.setBackground(new java.awt.Color(255, 0, 0));

        labelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        labelTitulo.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Seleccion de ruta para logs");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eleccionParaLogs, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eleccionParaLogs, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void configurarFileChooser() {

        eleccionParaLogs.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        eleccionParaLogs.addActionListener(e -> {

            String comando = e.getActionCommand();

            if (comando.equals(JFileChooser.APPROVE_SELECTION)) {

                File carpeta = eleccionParaLogs.getSelectedFile();
                String rutaLogs = carpeta.getAbsolutePath();
                

                JOptionPane.showMessageDialog(     this,"Ruta seleccionada: " + rutaLogs );
                contenedorSimulacion.getConstruirPartida().setPathHTML(rutaLogs);
                contenedorSimulacion.irAConfiguracionTiempos();
                
            }

            if (comando.equals(JFileChooser.CANCEL_SELECTION)) {
                JOptionPane.showMessageDialog( this, "Selección cancelada."  );
                contenedorSimulacion.irAEleccionDeDatos();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser eleccionParaLogs;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
