/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.Frontend.FrontendGestores;

import com.mycompany.Backend.GestorDeDatos.CreadorArchivosCSV;
import com.mycompany.Frontend.PanelesContenedores.ContenedorDatos;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Kenny
 */
public class CreadorDeDatosFrontend extends javax.swing.JPanel {

    private final ValidacionCreacionDeDatos validarDatos;
    private final ContenedorDatos contenedorDatos;
    
    
    public CreadorDeDatosFrontend(ContenedorDatos contenedorDatos) {
        this.validarDatos = new ValidacionCreacionDeDatos(this);
        this.contenedorDatos = contenedorDatos;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelTiempoDeMantenimiento = new javax.swing.JPanel();
        labelAvionGrande = new javax.swing.JLabel();
        labelAvionMediano = new javax.swing.JLabel();
        labelAvionPequeño = new javax.swing.JLabel();
        avionesGrande = new javax.swing.JTextField();
        avionesMedianos = new javax.swing.JTextField();
        avionesPequeños = new javax.swing.JTextField();
        panelNotas = new javax.swing.JPanel();
        labelNota = new javax.swing.JLabel();
        labelAviso1 = new javax.swing.JLabel();
        labelAviso2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combustibleGrande = new javax.swing.JTextField();
        combustibleMediano = new javax.swing.JTextField();
        combustiblePequeño = new javax.swing.JTextField();
        panelTituloConfi = new javax.swing.JPanel();
        labelCantidadAviones = new javax.swing.JLabel();
        panelTituloEstaciones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelEscionesPistas = new javax.swing.JPanel();
        labelPistaDeAterrizaje = new javax.swing.JLabel();
        pistasDeAterrizaje = new javax.swing.JTextField();
        labelPistaDespliegue = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cantidadPistasDespliegue = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        labelEstacionDeControl = new javax.swing.JLabel();
        cantidadEstacionesControl = new javax.swing.JTextField();
        labelDesbordaje = new javax.swing.JLabel();
        cantidadEstacionDesbordaje = new javax.swing.JTextField();
        labelEstacionMantenimiento = new javax.swing.JLabel();
        cantidadEstacionMantenimiento = new javax.swing.JTextField();
        capacidadDeAterrizaje = new javax.swing.JTextField();
        capacidadDeDespliegue = new javax.swing.JTextField();
        capacidadDeControl = new javax.swing.JTextField();
        capacidadDeDesbordaje = new javax.swing.JTextField();
        capacidadDeMantenimiento = new javax.swing.JTextField();
        labelNombreDeDatos = new javax.swing.JLabel();
        nombreDeDatos = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        botonGuardar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Creacion de datos");

        setBackground(new java.awt.Color(255, 204, 51));

        panelTitulo.setBackground(new java.awt.Color(255, 51, 51));

        labelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        labelTitulo.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("CREACION DE DATOS");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        labelTiempoDeMantenimiento.setBackground(new java.awt.Color(255, 153, 153));

        labelAvionGrande.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelAvionGrande.setForeground(new java.awt.Color(0, 0, 0));
        labelAvionGrande.setText("Grandes: ");

        labelAvionMediano.setBackground(new java.awt.Color(0, 0, 0));
        labelAvionMediano.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelAvionMediano.setForeground(new java.awt.Color(0, 0, 0));
        labelAvionMediano.setText("Medianos: ");

        labelAvionPequeño.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelAvionPequeño.setForeground(new java.awt.Color(0, 0, 0));
        labelAvionPequeño.setText("Pequeños: ");

        panelNotas.setBackground(new java.awt.Color(255, 51, 51));

        labelNota.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelNota.setForeground(new java.awt.Color(0, 0, 0));
        labelNota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNota.setText("NOTA: ");

        labelAviso1.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        labelAviso1.setForeground(new java.awt.Color(0, 0, 0));
        labelAviso1.setText("LA CAPACIDAD DE CADA AVION ES ALEATORIO Y PUEDEN TENER:");

        labelAviso2.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        labelAviso2.setForeground(new java.awt.Color(0, 0, 0));
        labelAviso2.setText("Grande: (30, 40), Mediano: (15, 25), Pequeño: (5, 10) (Pasajeros)");

        jLabel6.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("El tiempo de vuelo de cada avion se basa en su combustible");

        javax.swing.GroupLayout panelNotasLayout = new javax.swing.GroupLayout(panelNotas);
        panelNotas.setLayout(panelNotasLayout);
        panelNotasLayout.setHorizontalGroup(
            panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelAviso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelNotasLayout.createSequentialGroup()
                .addGroup(panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelAviso2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelNotasLayout.setVerticalGroup(
            panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotasLayout.createSequentialGroup()
                .addComponent(labelNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAviso1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAviso2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout labelTiempoDeMantenimientoLayout = new javax.swing.GroupLayout(labelTiempoDeMantenimiento);
        labelTiempoDeMantenimiento.setLayout(labelTiempoDeMantenimientoLayout);
        labelTiempoDeMantenimientoLayout.setHorizontalGroup(
            labelTiempoDeMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(labelTiempoDeMantenimientoLayout.createSequentialGroup()
                .addGroup(labelTiempoDeMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelAvionPequeño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAvionGrande, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAvionMediano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(labelTiempoDeMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(avionesGrande, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(avionesMedianos)
                    .addComponent(avionesPequeños))
                .addGap(18, 18, 18)
                .addGroup(labelTiempoDeMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combustibleGrande)
                    .addComponent(combustibleMediano)
                    .addComponent(combustiblePequeño, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        labelTiempoDeMantenimientoLayout.setVerticalGroup(
            labelTiempoDeMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelTiempoDeMantenimientoLayout.createSequentialGroup()
                .addGroup(labelTiempoDeMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAvionGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avionesGrande)
                    .addComponent(combustibleGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(labelTiempoDeMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAvionMediano, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avionesMedianos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combustibleMediano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(labelTiempoDeMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAvionPequeño, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avionesPequeños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combustiblePequeño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelTituloConfi.setBackground(new java.awt.Color(153, 255, 153));
        panelTituloConfi.setForeground(new java.awt.Color(153, 255, 153));

        labelCantidadAviones.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelCantidadAviones.setForeground(new java.awt.Color(0, 0, 0));
        labelCantidadAviones.setText("Cantidad de Aviones   - Combustible ");

        javax.swing.GroupLayout panelTituloConfiLayout = new javax.swing.GroupLayout(panelTituloConfi);
        panelTituloConfi.setLayout(panelTituloConfiLayout);
        panelTituloConfiLayout.setHorizontalGroup(
            panelTituloConfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloConfiLayout.createSequentialGroup()
                .addComponent(labelCantidadAviones, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelTituloConfiLayout.setVerticalGroup(
            panelTituloConfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCantidadAviones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelTituloEstaciones.setBackground(new java.awt.Color(204, 102, 255));

        jLabel2.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Estaciones y Pistas");

        jLabel3.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cantidades y capacidad maxima de aviones (de cada una).");

        javax.swing.GroupLayout panelTituloEstacionesLayout = new javax.swing.GroupLayout(panelTituloEstaciones);
        panelTituloEstaciones.setLayout(panelTituloEstacionesLayout);
        panelTituloEstacionesLayout.setHorizontalGroup(
            panelTituloEstacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );
        panelTituloEstacionesLayout.setVerticalGroup(
            panelTituloEstacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloEstacionesLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        panelEscionesPistas.setBackground(new java.awt.Color(0, 204, 204));

        labelPistaDeAterrizaje.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelPistaDeAterrizaje.setForeground(new java.awt.Color(0, 0, 0));
        labelPistaDeAterrizaje.setText("De aterrizaje: ");

        labelPistaDespliegue.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelPistaDespliegue.setForeground(new java.awt.Color(0, 0, 0));
        labelPistaDespliegue.setText("De despliegue: ");

        jLabel4.setFont(new java.awt.Font("Serif", 3, 19)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pistas (Cantidad y Capacidad)");

        jLabel5.setFont(new java.awt.Font("Serif", 3, 19)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Estaciones (Cantidad y Capacidad)");

        labelEstacionDeControl.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelEstacionDeControl.setForeground(new java.awt.Color(0, 0, 0));
        labelEstacionDeControl.setText("De control: ");

        labelDesbordaje.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelDesbordaje.setForeground(new java.awt.Color(0, 0, 0));
        labelDesbordaje.setText("De desbordaje: ");

        labelEstacionMantenimiento.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelEstacionMantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        labelEstacionMantenimiento.setText("De Mantenimiento: ");

        labelNombreDeDatos.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelNombreDeDatos.setForeground(new java.awt.Color(0, 0, 0));
        labelNombreDeDatos.setText("Nombre de carga de datos: ");

        javax.swing.GroupLayout panelEscionesPistasLayout = new javax.swing.GroupLayout(panelEscionesPistas);
        panelEscionesPistas.setLayout(panelEscionesPistasLayout);
        panelEscionesPistasLayout.setHorizontalGroup(
            panelEscionesPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelEscionesPistasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEscionesPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPistaDespliegue, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(labelPistaDeAterrizaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelEscionesPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pistasDeAterrizaje, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(cantidadPistasDespliegue))
                .addGap(18, 18, 18)
                .addGroup(panelEscionesPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(capacidadDeAterrizaje)
                    .addComponent(capacidadDeDespliegue, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
            .addComponent(labelNombreDeDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelEscionesPistasLayout.createSequentialGroup()
                .addGroup(panelEscionesPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelDesbordaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEstacionMantenimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEstacionDeControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEscionesPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cantidadEstacionesControl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(cantidadEstacionDesbordaje, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidadEstacionMantenimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEscionesPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(capacidadDeControl)
                    .addComponent(capacidadDeDesbordaje)
                    .addComponent(capacidadDeMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(nombreDeDatos)
        );
        panelEscionesPistasLayout.setVerticalGroup(
            panelEscionesPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscionesPistasLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEscionesPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPistaDeAterrizaje, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pistasDeAterrizaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacidadDeAterrizaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEscionesPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPistaDespliegue, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEscionesPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cantidadPistasDespliegue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(capacidadDeDespliegue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEscionesPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstacionDeControl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadEstacionesControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacidadDeControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEscionesPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDesbordaje, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadEstacionDesbordaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacidadDeDesbordaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEscionesPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstacionMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadEstacionMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacidadDeMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNombreDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panelBotones.setBackground(new java.awt.Color(204, 255, 0));
        panelBotones.setForeground(new java.awt.Color(204, 204, 0));

        botonGuardar.setBackground(new java.awt.Color(255, 153, 51));
        botonGuardar.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        botonGuardar.setText("Guardar datos");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonVolver.setBackground(new java.awt.Color(255, 51, 204));
        botonVolver.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(0, 0, 0));
        botonVolver.setText("Volver al menu");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTituloConfi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTiempoDeMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTituloEstaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEscionesPistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTituloEstaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTituloConfi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTiempoDeMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelEscionesPistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
            if (!validarDatos.validarNombre()) {
            JOptionPane.showMessageDialog(this,  "Debe ingresar un nombre para el conjunto de datos.");
            return;
        }

        if (!validarDatos.validarCantidadDeAviones()) {
            JOptionPane.showMessageDialog(this, "La cantidad de aviones debe ser numerica y mayor a 0.");
            return;
        }

        if (!validarDatos.validarCombustibleDeAviones()) {
            JOptionPane.showMessageDialog(this, "El combustible de los aviones debe ser numerico y mayor a 0.");
            return;
        }

        if (!validarDatos.validarCantidadDeAreas()) {
            JOptionPane.showMessageDialog(this,  "Las cantidades de pistas y estaciones deben ser numericas y mayores a 0.");
            return;
        }

        if (!validarDatos.validarCapacidadDeAreas()) {
            JOptionPane.showMessageDialog(this, "Las capacidades de areas deben ser numericas y mayores a 0.");
            return;
          }

        guardarDatos();

    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        reiniciarTextos();
        contenedorDatos.getVentanaPrincipal().irAMenuInicial();
    }//GEN-LAST:event_botonVolverActionPerformed

    

   private void guardarDatos() {
       
       CreadorArchivosCSV creadorDeDatos = new CreadorArchivosCSV(nombreDeDatos.getText());
       
       if (creadorDeDatos.verificarNombreRepetido()) {
            JOptionPane.showMessageDialog( this, "Ya existe un conjunto de datos con ese nombre.");
            return;
        }
       
        // Aviones
        creadorDeDatos.setCantidadDeAvionesGrandes(Integer.parseInt(avionesGrande.getText().trim()));
        creadorDeDatos.setCantidadDeAvionesMedianos( Integer.parseInt(avionesMedianos.getText().trim()));
        creadorDeDatos.setCantidadDeAvionesPequeños(Integer.parseInt(avionesPequeños.getText().trim()));

        // Combustible
        creadorDeDatos.setCombustibleGrande( Integer.parseInt(combustibleGrande.getText().trim()));
        creadorDeDatos.setCombustibleMediano( Integer.parseInt(combustibleMediano.getText().trim()));
        creadorDeDatos.setCombustiblePequeño( Integer.parseInt(combustiblePequeño.getText().trim()));

        // Cantidades de areasc
        creadorDeDatos.setCantidadPistasAterrizaje(  Integer.parseInt(pistasDeAterrizaje.getText().trim()));
        creadorDeDatos.setCantidadPistasDespegue( Integer.parseInt(cantidadPistasDespliegue.getText().trim()));
        creadorDeDatos.setCantidadEstacionesControl( Integer.parseInt(cantidadEstacionesControl.getText().trim()));
        creadorDeDatos.setCantidadEstacionDesbordaje( Integer.parseInt(cantidadEstacionDesbordaje.getText().trim()));
        creadorDeDatos.setCantidadEstacionMantenimiento(Integer.parseInt(cantidadEstacionMantenimiento.getText().trim()));

        // Capacidades
        creadorDeDatos.setCapacidadAterrizaje( Integer.parseInt(capacidadDeAterrizaje.getText().trim()));
        creadorDeDatos.setCapacidadDespegue( Integer.parseInt(capacidadDeDespliegue.getText().trim()));
        creadorDeDatos.setCapacidadControl( Integer.parseInt(capacidadDeControl.getText().trim()));
        creadorDeDatos.setCapacidadDesbordaje(  Integer.parseInt(capacidadDeDesbordaje.getText().trim()));
        creadorDeDatos.setCapacidadMantenimiento( Integer.parseInt(capacidadDeMantenimiento.getText().trim()));
        
        creadorDeDatos.guardarDatos();
        
        JOptionPane.showMessageDialog(this, "Datos guardados correctamente.");
        
        reiniciarTextos();
        
    }
   
   private void reiniciarTextos(){
       avionesGrande.setText("");
       avionesPequeños.setText("");
       avionesMedianos.setText("");
       combustibleGrande.setText("");
       combustiblePequeño.setText("");
       combustibleMediano.setText("");
       cantidadEstacionDesbordaje.setText("");
       cantidadEstacionMantenimiento.setText("");
       cantidadEstacionesControl.setText("");
       cantidadPistasDespliegue.setText("");
       capacidadDeAterrizaje.setText("");
       capacidadDeControl.setText("");
       capacidadDeDesbordaje.setText("");
       capacidadDeDespliegue.setText("");
       capacidadDeMantenimiento.setText("");
       pistasDeAterrizaje.setText("");
   }
   
    public JTextField getAvionesGrande() {
        return avionesGrande;
    }

    public JTextField getAvionesMedianos() {
        return avionesMedianos;
    }

    public JTextField getAvionesPequeños() {
        return avionesPequeños;
    }

    public JTextField getCantidadEstacionDesbordaje() {
        return cantidadEstacionDesbordaje;
    }

    public JTextField getCantidadEstacionMantenimiento() {
        return cantidadEstacionMantenimiento;
    }

    public JTextField getCantidadEstacionesControl() {
        return cantidadEstacionesControl;
    }

    public JTextField getCantidadPistasDespliegue() {
        return cantidadPistasDespliegue;
    }

    public JTextField getCapacidadDeAterrizaje() {
        return capacidadDeAterrizaje;
    }

    public JTextField getCapacidadDeControl() {
        return capacidadDeControl;
    }

    public JTextField getCapacidadDeDesbordaje() {
        return capacidadDeDesbordaje;
    }

    public JTextField getCapacidadDeDespliegue() {
        return capacidadDeDespliegue;
    }

    public JTextField getCapacidadDeMantenimiento() {
        return capacidadDeMantenimiento;
    }

    public JTextField getCombustibleGrande() {
        return combustibleGrande;
    }

    public JTextField getCombustibleMediano() {
        return combustibleMediano;
    }

    public JTextField getCombustiblePequeño() {
        return combustiblePequeño;
    }

    public JTextField getPistasDeAterrizaje() {
        return pistasDeAterrizaje;
    }

    public JTextField getNombreDeDatos() {
        return nombreDeDatos;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField avionesGrande;
    private javax.swing.JTextField avionesMedianos;
    private javax.swing.JTextField avionesPequeños;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextField cantidadEstacionDesbordaje;
    private javax.swing.JTextField cantidadEstacionMantenimiento;
    private javax.swing.JTextField cantidadEstacionesControl;
    private javax.swing.JTextField cantidadPistasDespliegue;
    private javax.swing.JTextField capacidadDeAterrizaje;
    private javax.swing.JTextField capacidadDeControl;
    private javax.swing.JTextField capacidadDeDesbordaje;
    private javax.swing.JTextField capacidadDeDespliegue;
    private javax.swing.JTextField capacidadDeMantenimiento;
    private javax.swing.JTextField combustibleGrande;
    private javax.swing.JTextField combustibleMediano;
    private javax.swing.JTextField combustiblePequeño;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelAvionGrande;
    private javax.swing.JLabel labelAvionMediano;
    private javax.swing.JLabel labelAvionPequeño;
    private javax.swing.JLabel labelAviso1;
    private javax.swing.JLabel labelAviso2;
    private javax.swing.JLabel labelCantidadAviones;
    private javax.swing.JLabel labelDesbordaje;
    private javax.swing.JLabel labelEstacionDeControl;
    private javax.swing.JLabel labelEstacionMantenimiento;
    private javax.swing.JLabel labelNombreDeDatos;
    private javax.swing.JLabel labelNota;
    private javax.swing.JLabel labelPistaDeAterrizaje;
    private javax.swing.JLabel labelPistaDespliegue;
    private javax.swing.JPanel labelTiempoDeMantenimiento;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField nombreDeDatos;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelEscionesPistas;
    private javax.swing.JPanel panelNotas;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelTituloConfi;
    private javax.swing.JPanel panelTituloEstaciones;
    private javax.swing.JTextField pistasDeAterrizaje;
    // End of variables declaration//GEN-END:variables
}
