/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Frontend.VentanaInicial;

import com.mycompany.Frontend.FrontendMenus.MenuInicial;
import com.mycompany.Frontend.PanelesContenedores.ContenedorDatos;
import com.mycompany.Frontend.PanelesDeEdicion.PanelContenedorEdicion;
import java.awt.CardLayout;


/**
 *
 * @author Kenny
 */
public class VentanaInicial extends javax.swing.JFrame {
    
    private final MenuInicial menuInicial;
    private final ContenedorDatos contenedorDeDatos;
    private final PanelContenedorEdicion contenedorEdicion;
    private final String CONTENEDOR_DE_DATOS = "CONTENEDOR DE DATOS";
    private final String CONTENEDOR_DE_EDICIONES = "CONTENEDOR DE EDICION";
    private final String MENU_INICIAL = "MENU INICIAL";

    /**
     * Creates new form VentanaInicial
     */
    public VentanaInicial() {
        this.menuInicial = new MenuInicial(this);
        this.contenedorDeDatos = new ContenedorDatos(this);
        this.contenedorEdicion = new PanelContenedorEdicion(this);
        
        initComponents();
        agregarPanelesPrincipales();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        irAMenuInicial();
    }
    
    private void agregarPanelesPrincipales(){
        PanelContenedor.add(contenedorDeDatos, CONTENEDOR_DE_DATOS);
        PanelContenedor.add(menuInicial, MENU_INICIAL);
        PanelContenedor.add(contenedorEdicion, CONTENEDOR_DE_EDICIONES);
    }
    
    private void cambiarDePaneles(String panel){
    CardLayout layout = (CardLayout) PanelContenedor.getLayout();
    layout.show(PanelContenedor, panel);
    }
    
    public void irAMenuDatos(){
        cambiarDePaneles(CONTENEDOR_DE_DATOS);
    }
    
    public  final void irAMenuInicial(){
        cambiarDePaneles(MENU_INICIAL);
    }
    
    public void irAEdicionDeDatos(){
        cambiarDePaneles(CONTENEDOR_DE_EDICIONES);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelContenedor = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContenedor.setBackground(new java.awt.Color(255, 51, 51));
        PanelContenedor.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public PanelContenedorEdicion getContenedorEdicion() {
        return contenedorEdicion;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
