/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.Frontend.FrontendMenus;

import com.mycompany.Frontend.PanelesContenedores.ContenedorDatos;

/**
 *
 * @author Kenny
 */
public class MenuDeDatos extends javax.swing.JPanel {

    private final ContenedorDatos contenedorDeDatos;
    
    public MenuDeDatos(ContenedorDatos contenedorDeDatos) {
        this.contenedorDeDatos = contenedorDeDatos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        panelContenedorDeBotones = new javax.swing.JPanel();
        botonCrearDatos = new javax.swing.JButton();
        botonEditarDatos = new javax.swing.JButton();
        botonVolverAlMenu = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 102));
        setForeground(new java.awt.Color(204, 255, 204));

        labelTitulo.setBackground(new java.awt.Color(255, 51, 51));
        labelTitulo.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("MENU DE DATOS");

        panelContenedorDeBotones.setBackground(new java.awt.Color(255, 255, 153));

        botonCrearDatos.setBackground(new java.awt.Color(255, 102, 102));
        botonCrearDatos.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        botonCrearDatos.setForeground(new java.awt.Color(0, 0, 0));
        botonCrearDatos.setText("Crear Datos");
        botonCrearDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearDatosActionPerformed(evt);
            }
        });

        botonEditarDatos.setBackground(new java.awt.Color(255, 0, 204));
        botonEditarDatos.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        botonEditarDatos.setForeground(new java.awt.Color(0, 0, 0));
        botonEditarDatos.setText("Editar Datos");

        botonVolverAlMenu.setBackground(new java.awt.Color(51, 102, 255));
        botonVolverAlMenu.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        botonVolverAlMenu.setForeground(new java.awt.Color(0, 0, 0));
        botonVolverAlMenu.setText("Volver al menu");
        botonVolverAlMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverAlMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContenedorDeBotonesLayout = new javax.swing.GroupLayout(panelContenedorDeBotones);
        panelContenedorDeBotones.setLayout(panelContenedorDeBotonesLayout);
        panelContenedorDeBotonesLayout.setHorizontalGroup(
            panelContenedorDeBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonCrearDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonEditarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonVolverAlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );
        panelContenedorDeBotonesLayout.setVerticalGroup(
            panelContenedorDeBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorDeBotonesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(botonCrearDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEditarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonVolverAlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(panelContenedorDeBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(panelContenedorDeBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearDatosActionPerformed
        // TODO add your handling code here
        contenedorDeDatos.irACreadorDeDatos();
        
    }//GEN-LAST:event_botonCrearDatosActionPerformed

    private void botonVolverAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverAlMenuActionPerformed
        // TODO add your handling code here:
        contenedorDeDatos.getVentanaPrincipal().irAMenuInicial();
    }//GEN-LAST:event_botonVolverAlMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearDatos;
    private javax.swing.JButton botonEditarDatos;
    private javax.swing.JButton botonVolverAlMenu;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelContenedorDeBotones;
    // End of variables declaration//GEN-END:variables
}
