/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.Frontend.PanelesSimulacion.PanelesDeInformacion;

import com.mycompany.Backend.Estaciones.EstacionDesbordaje;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kenny
 */
public class PanelInfoDesbordaje extends javax.swing.JPanel {

    private final EstacionDesbordaje estacionDesbordaje;
    /**
     * Creates new form PanelInfoDesbordaje
     * @param estacionDesbordaje
     */
    public PanelInfoDesbordaje(EstacionDesbordaje estacionDesbordaje) {
        this.estacionDesbordaje = estacionDesbordaje;
        
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAvionesDesbordaje = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        labelCapacidad = new javax.swing.JLabel();
        labelAvionEnTurno = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));

        tablaAvionesDesbordaje.setBackground(new java.awt.Color(204, 255, 102));
        tablaAvionesDesbordaje.setForeground(new java.awt.Color(204, 255, 204));
        tablaAvionesDesbordaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaAvionesDesbordaje);

        jLabel1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DESBORDAJE");

        labelID.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        labelID.setForeground(new java.awt.Color(0, 0, 0));
        labelID.setText("ID ESTACION: ");

        labelCapacidad.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        labelCapacidad.setForeground(new java.awt.Color(0, 0, 0));
        labelCapacidad.setText("CAPACIDAD: ");

        labelAvionEnTurno.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        labelAvionEnTurno.setForeground(new java.awt.Color(0, 0, 0));
        labelAvionEnTurno.setText("AVION EN TURNO: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(labelCapacidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAvionEnTurno, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAvionEnTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargarDatos() {
        labelID.setText("ID PISTA: " + estacionDesbordaje.getIdDeArea());
        labelCapacidad.setText("Capacidad: " + estacionDesbordaje.getCapacidadMaxima());
        
        labelAvionEnTurno.setText("Avion aterrizando: Ninguno");

        cargarTablaCola();
    }
    
    private void cargarTablaCola() {

        DefaultTableModel modelo = new DefaultTableModel(
            new String[]{"ID", "Tipo", "Combustible"},
            0
        );

        tablaAvionesDesbordaje.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAvionEnTurno;
    private javax.swing.JLabel labelCapacidad;
    private javax.swing.JLabel labelID;
    private javax.swing.JTable tablaAvionesDesbordaje;
    // End of variables declaration//GEN-END:variables
}
