/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.Frontend.PanelesSimulacion.PanelesDeInformacion;

import com.mycompany.Backend.Pistas.PistaDespegue;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kenny
 */
public class PanelInfoDespegue extends javax.swing.JPanel {

    private final PistaDespegue pista;
    
    /**
     * Creates new form PanelInfoDespegue
     * @param pista
     */
    public PanelInfoDespegue(PistaDespegue pista) {
        this.pista = pista;
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDespegue = new javax.swing.JTable();
        labelTitulo = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        labelCapacidad = new javax.swing.JLabel();
        labelAvionDespejando = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 51));

        tablaDespegue.setBackground(new java.awt.Color(204, 255, 153));
        tablaDespegue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDespegue);

        labelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        labelTitulo.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("PISTA DE DESPEGUE");

        labelID.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelID.setForeground(new java.awt.Color(0, 0, 0));
        labelID.setText("ID PISTA: ");

        labelCapacidad.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelCapacidad.setForeground(new java.awt.Color(0, 0, 0));
        labelCapacidad.setText("Capacidad: ");

        labelAvionDespejando.setBackground(new java.awt.Color(0, 0, 0));
        labelAvionDespejando.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        labelAvionDespejando.setForeground(new java.awt.Color(0, 0, 0));
        labelAvionDespejando.setText("Avion despejando: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(labelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelCapacidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelAvionDespejando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAvionDespejando, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
     private void cargarDatos() {
        labelID.setText("ID PISTA: " + pista.getIdDeArea());
        labelCapacidad.setText("Capacidad: " + pista.getCapacidadMaxima());
        
        labelAvionDespejando.setText("Avion aterrizando: Ninguno");

        cargarTablaCola();
    }
    
    private void cargarTablaCola() {

        DefaultTableModel modelo = new DefaultTableModel(
            new String[]{"ID", "Tipo", "Combustible"},
            0
        );

        tablaDespegue.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAvionDespejando;
    private javax.swing.JLabel labelCapacidad;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTable tablaDespegue;
    // End of variables declaration//GEN-END:variables
}
