/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.Frontend.PanelesDeEdicion;

import com.mycompany.Frontend.VentanaInicial.VentanaInicial;
import java.awt.CardLayout;
import java.io.File;

/**
 *
 * @author Kenny
 */
public final class PanelContenedorEdicion extends javax.swing.JPanel {

    private final VentanaInicial ventanaInicial;
    private final PanelMenuDeEdicion menuEditar;
    private final PanelEdicionDeArchivos editarArchivos;
    private final String EDITAR_ARCHIVOS = "EDITAR ARCHIVOS";
    private final String MENU_EDICION = "MENU EDICION";
    
    /**
     * Creates new form PanelContenedorEdicion
     * @param ventanaInicial
     */
    public PanelContenedorEdicion(VentanaInicial ventanaInicial) {
        this.ventanaInicial = ventanaInicial;
        this.menuEditar = new PanelMenuDeEdicion(ventanaInicial, this);
        this.editarArchivos = new PanelEdicionDeArchivos(this);
        initComponents();
        agregarPaneles();
        irAMenuEdicion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void agregarPaneles(){
        this.add(menuEditar, MENU_EDICION);
        this.add(editarArchivos, EDITAR_ARCHIVOS);
    }
    
    public void cambiarPaneles(String panel){
        CardLayout cardLayout = (CardLayout) this.getLayout();
        cardLayout.show(this, panel);
    }
    
    public void irAMenuEdicion(){
        cambiarPaneles(MENU_EDICION);
    }
    
    public void irAEdicion(String nombreDeArchivoElegido){
        editarArchivos.setArchivoElegido(nombreDeArchivoElegido);
        editarArchivos.editarTablas();
        cambiarPaneles(EDITAR_ARCHIVOS);
    }
    

    public PanelMenuDeEdicion getMenuEditar() {
        return menuEditar;
    }

    public VentanaInicial getVentanaInicial() {
        return ventanaInicial;
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
