/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.Frontend.PanelesSimulacion.ContenedoresDeDatos;

import com.mycompany.Backend.Aereopuerto.Aeropuerto;
import com.mycompany.Backend.Excepciones.ListaEnlazadaExcepcion;
import com.mycompany.Backend.ListaGenerica.ListaGenerica;
import com.mycompany.Backend.Pistas.PistaDeAterrizaje;
import com.mycompany.Backend.Pistas.PistaDespegue;
import com.mycompany.Frontend.PanelesSimulacion.PanelSimulacion;
import com.mycompany.Frontend.PanelesSimulacion.PanelesDeInformacion.PanelInfoAterrizaje;
import com.mycompany.Frontend.PanelesSimulacion.PanelesDeInformacion.PanelInfoDespegue;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Kenny
 */
public class PanelDespegue extends javax.swing.JPanel {

    private final PanelSimulacion panelSimulacion;
    
    /**
     * Creates new form PanelDespegue
     * @param panelSimulacion
     */
    public PanelDespegue(PanelSimulacion panelSimulacion) {
        this.panelSimulacion = panelSimulacion;
        initComponents();
        forzarScroll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        scrollInicial = new javax.swing.JScrollPane();
        panelCuadricula = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 204, 204));

        panelTitulo.setBackground(new java.awt.Color(255, 102, 102));

        labelTitulo.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("PISTAS DE DESPEGUE");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        panelCuadricula.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout panelCuadriculaLayout = new javax.swing.GroupLayout(panelCuadricula);
        panelCuadricula.setLayout(panelCuadriculaLayout);
        panelCuadriculaLayout.setHorizontalGroup(
            panelCuadriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
        );
        panelCuadriculaLayout.setVerticalGroup(
            panelCuadriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        scrollInicial.setViewportView(panelCuadricula);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollInicial)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollInicial))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void forzarScroll(){
        scrollInicial.setHorizontalScrollBarPolicy(    JScrollPane.HORIZONTAL_SCROLLBAR_NEVER );

         scrollInicial.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
         
         scrollInicial.getVerticalScrollBar().setUnitIncrement(20);
        }
    


   public void cargarCuadricula() {
        try {
            panelCuadricula.removeAll();
            panelCuadricula.setLayout(new FlowLayout(FlowLayout.LEFT, 15, 15));

            Aeropuerto aeropuerto = panelSimulacion
                    .getPanelContenedorSimulacion()
                    .getSimulacion()
                    .getAeropuerto();

            ListaGenerica<PistaDespegue> pistas =
                    aeropuerto.getPistasDeDespegue();

            for (int i = 0; i < pistas.getTamañoDeLista(); i++) {
                PistaDespegue pista = pistas.obtenerContenido(i);

                PanelInfoDespegue panel = new PanelInfoDespegue(pista);
                panelCuadricula.add(panel);
            }

            int columnas = 3;
            int filas = (int) Math.ceil(
                    pistas.getTamañoDeLista() / (double) columnas
            );

            int alturaCelda = 300;
            int separacion = 15;
            int alturaTotal = filas * (alturaCelda + separacion * 2);

            panelCuadricula.setPreferredSize(
                    new Dimension(1000, alturaTotal)
            );

            panelCuadricula.revalidate();
            panelCuadricula.repaint();

        } catch (ListaEnlazadaExcepcion e) {
                JOptionPane.showMessageDialog(
                        this,
                        "Error al cargar pistas: " + e.getMessage()
                );
            }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelCuadricula;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JScrollPane scrollInicial;
    // End of variables declaration//GEN-END:variables
}
