/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.Frontend.PanelesSimulacion.ContenedoresDeDatos;

import com.mycompany.Backend.Aereopuerto.Aeropuerto;
import com.mycompany.Backend.Aviones.Avion;
import com.mycompany.Backend.Excepciones.ListaEnlazadaExcepcion;
import com.mycompany.Backend.ListaGenerica.ListaGenerica;
import com.mycompany.Frontend.PanelesSimulacion.PanelSimulacion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kenny
 */
public class PanelDeVuelo extends javax.swing.JPanel {

    private final PanelSimulacion panelSimulacion;
    
    /**
     * Creates new form PanelDeVuelo
     * @param panelSimulacion
     */
    public PanelDeVuelo(PanelSimulacion panelSimulacion){
        this.panelSimulacion = panelSimulacion;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEstadoDeAviones = new javax.swing.JTable();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 102));

        TablaEstadoDeAviones.setBackground(new java.awt.Color(102, 255, 153));
        TablaEstadoDeAviones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaEstadoDeAviones);

        panelTitulo.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estado de aviones");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    public final void mostrarDatosTabla() {

        try {
            Aeropuerto aeropuerto = panelSimulacion .getPanelContenedorSimulacion() .getSimulacion()   .getAeropuerto();

            DefaultTableModel modelo = new DefaultTableModel(
                    new String[]{"Tipo", "ID", "Combustible", "Estado"},
                    0
            );

            cargarAvionesEnTabla(modelo, aeropuerto.getAvionesPequeños());
            cargarAvionesEnTabla(modelo, aeropuerto.getAvionesMedianos());
            cargarAvionesEnTabla(modelo, aeropuerto.getAvionesGrandes());

            TablaEstadoDeAviones.setModel(modelo);

        } catch (ListaEnlazadaExcepcion e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error cargando datos de aviones."
            );

            e.printStackTrace();
        }
    }
    
   private void cargarAvionesEnTabla(  DefaultTableModel modelo, ListaGenerica<Avion> listaAviones) throws ListaEnlazadaExcepcion {

        for (int i = 0; i < listaAviones.getTamañoDeLista(); i++) {

            Avion avion = listaAviones.obtenerContenido(i);

            Object[] fila = {
                avion.getTipo(),
                avion.getIdAvion(),
                avion.getCombustible(),
                avion.getControladorAvion().getEstadoDeAvion()
            };

            modelo.addRow(fila);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaEstadoDeAviones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
