/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.Frontend.PanelesContenedores;

import com.mycompany.Frontend.FrontendGestores.CreadorDeDatosFrontend;
import com.mycompany.Frontend.FrontendMenus.MenuDeDatos;
import com.mycompany.Frontend.VentanaInicial.VentanaInicial;
import java.awt.CardLayout;

/**
 *
 * @author Kenny
 */
public class ContenedorDatos extends javax.swing.JPanel {

    private final VentanaInicial ventanaPrincipal;
    private final CreadorDeDatosFrontend crearDatosFrontend;
    private final MenuDeDatos menuDeDatos;
    private final String CREADOR_DE_DATOS = "DATOS";
    private final String MENU_DE_DATOS = "MENU DE DATOS";
    
    /**
     * Creates new form PanelContenedorDeDatos
     * @param ventanaPrincipal
     */
    public ContenedorDatos(VentanaInicial ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
        this.crearDatosFrontend = new CreadorDeDatosFrontend(this);
        this.menuDeDatos = new MenuDeDatos(this);
        initComponents();
        agregarPaneles();
        irAMenuDeDatos();
    }
    
    private void agregarPaneles(){
        this.add(crearDatosFrontend, CREADOR_DE_DATOS);
        this.add(menuDeDatos, MENU_DE_DATOS);
    }
    
    private void cambiarDePaneles(String panel){
        CardLayout cardLayout = (CardLayout) this.getLayout();
        cardLayout.show(this, panel);
    }
    
    public void irACreadorDeDatos(){
        cambiarDePaneles(CREADOR_DE_DATOS);
    }
    
    public final void irAMenuDeDatos(){
        cambiarDePaneles(MENU_DE_DATOS);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents

    public VentanaInicial getVentanaPrincipal() {
        return ventanaPrincipal;
    }
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
